// <auto-generated />
using System;
using Eshop.Server.Infrastructure.Persistenza;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eshop.Server.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251105090322_NomeMigrazione")]
    partial class NomeMigrazione
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Carrello", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimoAggiornamentoPrezziUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("Carrelli");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("QuantitaDisponibile")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Prodotti");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.VoceCarrello", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrelloId")
                        .HasColumnType("int");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdottoId");

                    b.HasIndex("CarrelloId", "ProdottoId")
                        .IsUnique();

                    b.ToTable("VociCarrello");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.VoceOrdine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeProdotto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<int>("ProdottoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdineId");

                    b.ToTable("VociOrdine");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Carrello", b =>
                {
                    b.HasOne("Eshop.Server.Domain.Modelli.Utente", "Cliente")
                        .WithOne("Carrello")
                        .HasForeignKey("Eshop.Server.Domain.Modelli.Carrello", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Ordine", b =>
                {
                    b.HasOne("Eshop.Server.Domain.Modelli.Utente", "Cliente")
                        .WithMany("Ordini")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Prodotto", b =>
                {
                    b.OwnsOne("Eshop.Server.Domain.OggettiValore.Money", "Prezzo", b1 =>
                        {
                            b1.Property<int>("ProdottoId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Valore")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Prezzo");

                            b1.Property<string>("Valuta")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("Valuta");

                            b1.HasKey("ProdottoId");

                            b1.ToTable("Prodotti");

                            b1.WithOwner()
                                .HasForeignKey("ProdottoId");
                        });

                    b.Navigation("Prezzo")
                        .IsRequired();
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Utente", b =>
                {
                    b.OwnsOne("Eshop.Server.Domain.OggettiValore.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UtenteId")
                                .HasColumnType("int");

                            b1.Property<string>("Valore")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("varchar(256)")
                                .HasColumnName("Email");

                            b1.HasKey("UtenteId");

                            b1.HasIndex("Valore")
                                .IsUnique();

                            b1.ToTable("Utenti");

                            b1.WithOwner()
                                .HasForeignKey("UtenteId");
                        });

                    b.OwnsOne("Eshop.Server.Domain.OggettiValore.Indirizzo", "Indirizzo", b1 =>
                        {
                            b1.Property<int>("UtenteId")
                                .HasColumnType("int");

                            b1.Property<string>("CAP")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("CAP");

                            b1.Property<string>("Citta")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Citta");

                            b1.Property<string>("Telefono")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("Telefono");

                            b1.Property<string>("Via")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Via");

                            b1.HasKey("UtenteId");

                            b1.ToTable("Utenti");

                            b1.WithOwner()
                                .HasForeignKey("UtenteId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Indirizzo");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.VoceCarrello", b =>
                {
                    b.HasOne("Eshop.Server.Domain.Modelli.Carrello", "Carrello")
                        .WithMany("Voci")
                        .HasForeignKey("CarrelloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eshop.Server.Domain.Modelli.Prodotto", "Prodotto")
                        .WithMany()
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Eshop.Server.Domain.OggettiValore.Money", "PrezzoUnitarioSnapshot", b1 =>
                        {
                            b1.Property<int>("VoceCarrelloId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Valore")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrezzoSnapshot");

                            b1.Property<string>("Valuta")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("ValutaSnapshot");

                            b1.HasKey("VoceCarrelloId");

                            b1.ToTable("VociCarrello");

                            b1.WithOwner()
                                .HasForeignKey("VoceCarrelloId");
                        });

                    b.OwnsOne("Eshop.Server.Domain.OggettiValore.Quantita", "Quantita", b1 =>
                        {
                            b1.Property<int>("VoceCarrelloId")
                                .HasColumnType("int");

                            b1.Property<int>("Valore")
                                .HasColumnType("int")
                                .HasColumnName("Quantita");

                            b1.HasKey("VoceCarrelloId");

                            b1.ToTable("VociCarrello");

                            b1.WithOwner()
                                .HasForeignKey("VoceCarrelloId");
                        });

                    b.Navigation("Carrello");

                    b.Navigation("PrezzoUnitarioSnapshot")
                        .IsRequired();

                    b.Navigation("Prodotto");

                    b.Navigation("Quantita")
                        .IsRequired();
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.VoceOrdine", b =>
                {
                    b.HasOne("Eshop.Server.Domain.Modelli.Ordine", "Ordine")
                        .WithMany("Voci")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Eshop.Server.Domain.OggettiValore.Money", "PrezzoUnitario", b1 =>
                        {
                            b1.Property<int>("VoceOrdineId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Valore")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrezzoUnitario");

                            b1.Property<string>("Valuta")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasColumnName("Valuta");

                            b1.HasKey("VoceOrdineId");

                            b1.ToTable("VociOrdine");

                            b1.WithOwner()
                                .HasForeignKey("VoceOrdineId");
                        });

                    b.Navigation("Ordine");

                    b.Navigation("PrezzoUnitario")
                        .IsRequired();
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Carrello", b =>
                {
                    b.Navigation("Voci");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Ordine", b =>
                {
                    b.Navigation("Voci");
                });

            modelBuilder.Entity("Eshop.Server.Domain.Modelli.Utente", b =>
                {
                    b.Navigation("Carrello");

                    b.Navigation("Ordini");
                });
#pragma warning restore 612, 618
        }
    }
}
